os: linux
language: scala

jobs:
  include:
    - language: scala
      stage: Full Coverage
      jdk: openjdk11
      install: export TRAVIS_WORKER_DOCKER_MEMORY=16G
      scala:
        - 2.13
      script:
        - nvm install 12
        - nvm use 12
        - yarn config set workspaces-experimental true
        - yarn install
        - jest --coverage
        - travis_wait 30 sbt "project service" clean update coverage test
        - travis_wait 30 sbt "project service" jacoco coverageAggregate coverageReport coveralls
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial $(find **/jacoco*.xml -printf '-r %p ')
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial $(find **/lcov.info -printf '-r %p ')
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) final

    - language: node_js
      stage: Frontend Test (Angular Nebular Release)
      node_js: 12
      script:
        - yarn config set workspaces-experimental true
        - yarn install
        - jest --coverage && coveralls < coverage/lcov.info
        - codecov

    - language: scala
      stage: Backend Test (All Scala 2.13.1 Services)
      jdk: openjdk11
      install: export TRAVIS_WORKER_DOCKER_MEMORY=16G
      scala:
        - 2.13
      script:
        - export COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN}
        - travis_wait 30 sbt "project service" clean update coverage test
        - travis_wait 30 sbt "project service" jacoco coverageAggregate coverageReport coveralls
        - bash <(curl -s https://codecov.io/bash)
