name: Update sbt dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup sdkman
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdkman_auto_answer=false
          sdkman_selfupdate_enable=false

      - name: Setup sbt
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install sbt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Run dependency update script
        run: make deps-update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update sbt dependencies
          branch: update-sbt-dependencies
          title: 'Update sbt dependencies'
          body: |
            This pull request updates the following dependencies:
            - Dependency updates

          labels: dependencies
